### ISSUE TITLE
Request endpoint Filter Ayat

### ISSUE THREAD

**Issue by Sansekai** [renomureza/quran-api-id#120]
**Apakah permintaan fitur Anda terkait dengan masalah?** Saya memiliki masalah dimana saat menampilkan data contohnya surah 1 dengat ayat 1-5 yang dimana untuk ayat 6 - 7 tidak saya ambil maka saya merequest endpoint untuk memfilter ayat.
Saya merequest ini karena saya mengalami kesulitan ketika menampilkan ratusan ayat dari suatu surah.

**Jelaskan solusi yang Anda inginkan**
Contohnya saya ingin menampilkan surah 1 dan ayat hanya 1-5 maka endpointnya seperti ini ``/surahs/{nomorSurah}/ayahs/{nomorAyatAwal}-{nomorAyatAkhir}`` jadi ``/surahs/1/ayahs/1-5``

**Comment by fitrahmunir** [comment]
Saya mau coba bantu, sepertinya untuk endpoint range ayat yang possible akan seperti ini

```
/surahs/{nomorSurah}/ayahs?from={nomorAyatAwal}&to={nomorAyatAkhir}
```

Jadi contoh endpointnya seperti ini

```
/surahs/1/ayahs?from=1&to=5
```

Bila berkenan untuk saya bantu, boleh set assignee nya ke saya. Terima kasih.

*Notes: Issue ini juga sama seperti issue yang sudah dibuat sebelumnnya https://github.com/renomureza/quran-api-id/issues/56
